on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install deps
        run: |
          gem install bundler
          bundle install
      -
        name: Build
        run: |
          ruby main.rb ${{ inputs.version }}
      -
        name: Choco Pack
        run: |
          cd rainforest-cli/
          choco pack
